apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "shoreline.fullname" . }}-externalsecret
  namespace: shoreline{{ .Values.runEnv }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: systems-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: {{ include "shoreline.fullname" . }}-secrets
  data:
    - secretKey: "GEOSERVER_ADMIN_PASSWORD"
      remoteRef:
        key: {{ .Values.existingSecret.externalSecrets.geoserver_admin_passwd }}
    - secretKey: "POSTGRES_PASSWORD"
      remoteRef:
        key: {{ .Values.existingSecret.externalSecrets.db_passwd }}
    - secretKey: "POSTGRES_USER"
      remoteRef:
        key: {{ .Values.existingSecret.externalSecrets.db_username }}
    - secretKey: "SECRET_KEY_BASE"
      remoteRef:
        key: {{ .Values.existingSecret.externalSecrets.secret_key_base }}
    - secretKey: "SMTP_PASSWORD"
      remoteRef:
        key: {{ .Values.existingSecret.externalSecrets.smtp_password }}
    - secretKey: "SOLR_URL"
      remoteRef:
        key: {{ .Values.existingSecret.externalSecrets.solr_url }}
